### ISSUE TITLE
May not be compatible with Windows

### ISSUE THREAD

**Issue by ferventcoder** [voxpupuli/puppet-nodejs#265]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Any on Windows
- Module version: 0.8.0

I do realize this is/was an issue with https://forge.puppet.com/puppetlabs/nodejs/0.8.0/readme and there have since been many releases under https://forge.puppet.com/puppet/nodejs.

Has the behavior been fixed?

## How to reproduce (e.g Puppet code you use)

From a Windows box that has the module without npm installed:
`puppet resource package `

## What are you seeing
Errors

## What behaviour did you expect instead
For it to work, or disable itself as non-suitable.

## Output log

~~~sh
Debug: Executing: ' list --json --global'
Error: Could not run: The parameter is incorrect. - CreateProcess
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/2.1.0/gems/win32-process-0.7.4/lib/win32/process.rb:685:in `
reate'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util/windows/process.rb:12:in `execute'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util/execution.rb:321:in `block in execute_windows'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util.rb:128:in `withenv'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util/execution.rb:320:in `execute_windows'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/util/execution.rb:214:in `execute'
C:/Program Files/Puppet Labs/Puppet/puppet/lib/puppet/provider.rb:107:in `execute'
C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet/provider/package/npm.rb:19:in `npmlist'
C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet/provider/package/npm.rb:36:in `instances'
~~~

## Any additional information you'd like to impart
https://puppetcommunity.slack.com/archives/windows/p1481822480000065

**Comment by ferventcoder** [comment]
Looks like this may have been fixed.

**Comment by ferventcoder** [comment]
I'm going to preemptively close this because it appears fixed in the non-puppetlabs releases of the module. Leaving it here for anyone that runs into this issue and goes searching.
